version: '3.4'
networks:
  constr-sw-2022-2:
volumes:
  keycloak-data:
    external: true
  mongodb-data:
    external: true
  postgresql-data:
    external: true
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  auth:
    container_name: auth
    build: ./auth
    environment:
      - KEYCLOAK_PORT=8090
      - AUTH_SERVER_PORT=8091
    ports:
      - "8091:8091"
    networks:
      - constr-sw-2022-2
    depends_on:
      - keycloak
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=a12345678
    volumes:
      - mongodb-data:/data/mongodb
    networks:
      - constr-sw-2022-2
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=a12345678
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - constr-sw-2022-2
  # # grupo1
  # buildings-api:
  #   container_name: predios-api
  #   ports:
  #     - 8081:8080
  #   depends_on:
  #     - auth
  #     - mongodb OU postgresql
  #     - recursos-api
  # # grupo2
  # recursos-api:
  #   container_name: predios-api
  #   ports:
  #     - 8082:8080
  #   depends_on:
  #     - auth
  #     - mongodb OU postgresql
  #     - recursos-api
  # # grupo3
  # reservas-api:
  #   container_name: reservas-api
  #   ports:
  #     - 8083:8080
  #   depends_on:
  #     - auth
  #     - mongodb OU postgresql
  #     - recursos-api
  # # grupo5
  # turmas-api:
  #   container_name: turmas-api
  #   ports:
  #     - 8085:8080
  #   depends_on:
  #     - auth
  #     - mongodb OU postgresql
  #     - recursos-api
  # # grupo6
  # disciplinas-api:
  #   container_name: disciplinas-api
  #   ports:
  #     - 8086:8080
  #   depends_on:
  #     - auth
  #     - postgresql
  # grupo7
  classes-api:
    container_name: classes-api
    build: ./backend/classes/classes-ms
    environment:
      - SERVER_PORT=8092
    ports:
      - 8087:8092
    networks:
      - constr-sw-2022-2
    depends_on:
      - auth
      - postgresql
