version: '3.4'
networks:
  constr-sw-2022-2:
volumes:
  keycloak-data:
    external: true
  mongodb-data:
    external: true
  postgresql-data:
    external: true
services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a12345678
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - constr-sw-2022-2
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=a12345678
    volumes:
      - mongodb-data:/data/mongodb
    networks:
      - constr-sw-2022-2
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  auth:
    container_name: auth
    build: ./backend/lessons/auth
    environment:
      - KEYCLOAK_PORT=8090
      - KEYCLOAK_CLIENT_ID=grupo7
      - KEYCLOAK_CLIENT_SECRET=HjTtaSOS39LaQ62HcUC1hZo6CC16q3f2
      - AUTH_SERVER_PORT=8080
    ports:
      - 8080:8080
    networks:
      - constr-sw-2022-2
    depends_on:
      - keycloak
  # grupo1: PRÉDIOS E SALAS
  buildings-api:
    container_name: buildings-api
    build: ./backend/buildings/buildings-classrooms
    environment:
      - API_PORT=8081
      - KEYCLOAK_API_HOST=auth
      - KEYCLOAK_API_PORT=8080
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
    ports:
      - 8081:8081
    networks:
      - constr-sw-2022-2
    depends_on:
      - mongodb
  # grupo2: RECURSOS
  resources-api:
    container_name: resources-api
    build: ./backend/resources/resources-api
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=a12345678
      - SPRING_CONFIG_LOCATION=/app/src/main/resources/application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/
    ports:
      - 8082:8082
    networks:
      - constr-sw-2022-2
    depends_on:
      - postgresql
  # grupo3: RESERVAS
  reservations-api:
    container_name: reservations-api
    build: ./backend/reservations/reservations-api
    ports:
      - 8083:8083
    environment:
      - NODE_ENV=production
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=a12345678
      - KEYCLOAK_API_SERVER_URL=http://keycloak-api:3000
      - RESOURCES_API_SERVER_URL=http://resources-api:8082
      - RESOURCES_API_MOCK=true
    networks:
      - constr-sw-2022-2
    depends_on:
      - postgresql
  # grupo5: TURMAS
  classes-api:
    container_name: classes-api
    build: ./backend/classes/classrooms
    environment:
      - KEYCLOAK_API_HOST=auth
      - KEYCLOAK_API_PORT=8080
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=a12345678
      - API_PORT=8085
    ports:
      - 8085:8085
    networks:
      - constr-sw-2022-2
    depends_on:
      - mongodb
  # grupo6: DISCIPLINAS
  courses-api:
    container_name: courses-api
    build: ./backend/courses/disciplines
    environment:
      - KEYCLOAK_API_HOST=auth
      - KEYCLOAK_API_PORT=8080
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=a12345678
      - API_PORT=8086
    ports:
      - 8086:8086
    networks:
      - constr-sw-2022-2
    depends_on:
      - mongodb
  # grupo7: AULAS
  lessons-api:
    container_name: lessons-api
    build: ./backend/lessons/classes-ms
    environment:
      - SERVER_PORT=8080
      - SWAGGER_CUSTOM_SERVER=https://8092-pucrspoli-constrsw20222-5uwu1stt2g9.ws-us77.gitpod.io
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a12345678
      - SERVICE_ROOMS_MOCKED=false
      - SERVICE_GROUPS_MOCKED=true
      - SERVICE_RESERVATIONS_MOCKED=false
    ports:
      - 8087:8080
    networks:
      - constr-sw-2022-2
    depends_on:
      - postgresql
  # frontend
  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - PORT=80
      - ENV_NAME=production
    ports:
      - 80:80
    networks:
      - constr-sw-2022-2
    depends_on:
      - auth
      - buildings-api
      - resources-api
      - reservations-api
      - classes-api
      - courses-api
      - lessons-api
